version: 2.1

jobs:
  test:
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Test
          command:  |
                  pip install pytest
                  pytest


workflows:
  version: 2.1
  build:
    jobs:
      - test